<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_flaskBlog</name>
   <tag></tag>
   <elementGuidId>7761e819-894c-447d-adaa-2b2cf7cf7c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='🌞'])[1]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.btn.btnLink.btnHome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2cf6cfe2-af39-430b-ae06-e6d04ddb38b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnLink btnHome</value>
      <webElementGuid>faff2994-e403-44e1-8547-4bdf6f8759f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>flaskBlog</value>
      <webElementGuid>45929dc0-9f2a-4141-b8de-d97d4550d3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;navbar&quot;]/a[1]/h1[@class=&quot;btn btnLink btnHome&quot;]</value>
      <webElementGuid>21142f30-ce49-4b9a-9ca4-082e7504b482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🌞'])[1]/following::h1[1]</value>
      <webElementGuid>95df66c1-4951-445a-90cb-d1716f093f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🔍'])[1]/preceding::h1[1]</value>
      <webElementGuid>7ca94ccf-7240-407f-96e8-c21fa625e672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::h1[1]</value>
      <webElementGuid>d95afc91-6ea8-4373-96c2-0e7bd5ad3a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='flaskBlog']/parent::*</value>
      <webElementGuid>8be7dab4-ec72-4b3a-a5d3-bf21bfe902f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>ae9d39df-044f-4224-95da-79b7f5f07f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'flaskBlog' or . = 'flaskBlog')]</value>
      <webElementGuid>ba8aad33-edf9-4a82-9735-076c579c1a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
