<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Paragraph</name>
   <tag></tag>
   <elementGuidId>6358c4c9-dcf8-4756-9e0a-1b0f4ea03ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ck.ck-button.ck-off.ck-button_with-text.ck-dropdown__button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d1e7e71-2a7e-49eb-97a1-10291abd0264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ck ck-button ck-off ck-button_with-text ck-dropdown__button</value>
      <webElementGuid>c6bdcdae-4270-443b-b462-9f65c761b083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9052749-4a77-4463-9da2-9035007212f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7b404d3f-9992-47c1-852a-1038b163c39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ck-editor__aria-label_ee7e3a7e799efbd4e3afe34b410c19472</value>
      <webElementGuid>0ee16307-d475-4733-8fb5-5d1ad71654b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cke-tooltip-text</name>
      <type>Main</type>
      <value>Heading</value>
      <webElementGuid>20666093-5351-4c2c-9ea1-e4193a3d579c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cke-tooltip-position</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>eeb51498-f880-49df-9454-a25bf55c9e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f493063-7db7-48c5-99a3-361633287c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b24b451-931d-43d6-99c8-7384d7e50afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paragraph</value>
      <webElementGuid>6ff9597e-94a3-47c7-9532-d4e9ae058292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/form[@class=&quot;form formPost centeredHorizontally&quot;]/div[@class=&quot;ck ck-reset ck-editor ck-rounded-corners&quot;]/div[@class=&quot;ck ck-editor__top ck-reset_all&quot;]/div[@class=&quot;ck ck-sticky-panel&quot;]/div[@class=&quot;ck ck-sticky-panel__content&quot;]/div[@class=&quot;ck ck-toolbar ck-toolbar_grouping&quot;]/div[@class=&quot;ck ck-toolbar__items&quot;]/div[@class=&quot;ck ck-dropdown ck-heading-dropdown&quot;]/button[@class=&quot;ck ck-button ck-off ck-button_with-text ck-dropdown__button&quot;]</value>
      <webElementGuid>a7b00a02-c9d1-4087-8dc7-3445da64e801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>f4ba99af-b24e-49da-85a8-720b73aee6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rich Text Editor'])[1]/following::button[1]</value>
      <webElementGuid>0b686209-18b2-476b-bb1b-89b411d708a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(separete with comma)'])[1]/following::button[1]</value>
      <webElementGuid>19aafc08-8c11-4a0c-bb98-82f0f10b25a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paragraph'])[2]/preceding::button[1]</value>
      <webElementGuid>2b72d54c-c0b5-4921-b1e9-1c3e7b72c383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>d7c16db2-7e1d-4537-96de-62e608fdf721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Paragraph' or . = 'Paragraph')]</value>
      <webElementGuid>743266ea-5d42-4c45-a6d5-df2e4518f637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
