<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_postTags</name>
   <tag></tag>
   <elementGuidId>b673a9a0-7cef-458f-bdde-c987460ab69b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postTags']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#postTags</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6bee10d0-e51a-4635-81cf-5f7865bf56c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>21b97145-a3a3-4cb5-8918-3e80cb600ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input centeredHorizontally</value>
      <webElementGuid>4df71acd-f32c-431f-90c8-76f18b4c8d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postTags</value>
      <webElementGuid>f7a5adc7-b5f6-4237-8dd8-8aea70555c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postTags</value>
      <webElementGuid>039e6f32-624c-444f-874b-fd9268239d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>tags</value>
      <webElementGuid>aac2b55a-2f2e-4461-b4a1-b468147ddac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ae4c8d3-661e-43ca-8bdc-3d4c90d7f2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postTags&quot;)</value>
      <webElementGuid>837a8efe-eb59-4746-963f-f58ca412697b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postTags']</value>
      <webElementGuid>3ddeeb57-e126-47c1-9dc8-b8057d625134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>84cf3acd-42a8-43f2-8b9b-850c8b09581f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'postTags' and @name = 'postTags' and @placeholder = 'tags' and @type = 'text']</value>
      <webElementGuid>d9f9a837-83d7-4b2a-9ea3-e1aa3fdd362c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
