<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_passwordConfirm</name>
   <tag></tag>
   <elementGuidId>02c6262a-02e7-4cf5-9f0d-6f6bad1748db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordConfirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#passwordConfirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>367aebf7-c793-4ec7-b925-0e8e5468437c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>462a4bfe-4d60-4c2a-8f71-c05f982ef892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordConfirm</value>
      <webElementGuid>fb72aa1b-b879-4656-b9e4-20a4238a5dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>decab3ed-2b97-4e3a-816a-756476068b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passwordConfirm</value>
      <webElementGuid>303a7cb5-ecfb-46db-a942-1a664deffb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>confirm your password</value>
      <webElementGuid>a56c2bbf-2b7a-4843-b087-62ab68283d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4d528d8e-867e-4042-a435-be585614b2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordConfirm&quot;)</value>
      <webElementGuid>754b6450-a65b-41d2-9ba7-e712f6c9f121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordConfirm']</value>
      <webElementGuid>0dcfaa8f-e500-4d3a-b418-9c09f44e557e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>919d15d9-6456-41f2-b524-1050edd92e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'passwordConfirm' and @name = 'passwordConfirm' and @placeholder = 'confirm your password' and @type = 'password']</value>
      <webElementGuid>152b658b-bfc8-4dd4-b934-763cf9f68c34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
