<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_fail_message</name>
   <tag></tag>
   <elementGuidId>a1c5cee2-43fa-4b6b-a2d6-6fceb631d028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flashContainer > p.error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#flash.error</value>
      <webElementGuid>09d39a90-4790-43c9-b75b-9abd53332bbd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
