<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Depremler</name>
   <tag></tag>
   <elementGuidId>a340ebb7-ecc5-4045-9d66-2dfcc9426464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Depremler')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.title.textPrimary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e995d62c-de73-422f-b47f-d6248c3a068d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title textPrimary</value>
      <webElementGuid>df3634b0-b4d2-47de-9244-0eea1b78bc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>post/1</value>
      <webElementGuid>9732d103-bbb1-4b29-a5bf-de459e71d437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Depremler</value>
      <webElementGuid>f57ba346-5c16-4bce-848b-ccfc90a1c95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;post centeredHorizontally&quot;]/a[@class=&quot;title textPrimary&quot;]</value>
      <webElementGuid>9a1dacc9-1743-41f7-aff4-92ff1b739b88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Depremler')]</value>
      <webElementGuid>23a9818f-4454-4e05-bfce-c8b24fda75ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[1]</value>
      <webElementGuid>e7b041be-1308-49f3-995c-26a2f79182b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[2]</value>
      <webElementGuid>3382834d-6b48-4f66-80f3-ca80e7179701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Depremler']/parent::*</value>
      <webElementGuid>b6bf1854-fa84-4ff8-a8da-58e2b3cc8173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'post/1')]</value>
      <webElementGuid>b291a23c-1706-4ff2-b4da-5b37c20ae114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>f7e3bfa8-248b-488b-9dee-fd17af5ef0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'post/1' and (text() = 'Depremler' or . = 'Depremler')]</value>
      <webElementGuid>b22f1ac7-b2df-4035-85d6-e6d64ba40729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
