<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_flaskBlog</name>
   <tag></tag>
   <elementGuidId>c39dbfb4-3799-4891-96c7-f8edaaaa8ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='🌞'])[1]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.btn.btnLink.btnHome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>19d3a8f6-40e5-4738-8d78-1bcd1b613bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnLink btnHome</value>
      <webElementGuid>9d7562f3-798f-42d3-b3cd-6d3b5438bbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>flaskBlog</value>
      <webElementGuid>b41fc38b-03ec-4519-8803-25006fa4c634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;navbar&quot;]/a[1]/h1[@class=&quot;btn btnLink btnHome&quot;]</value>
      <webElementGuid>428fd36c-2aaf-407b-99ca-4ff7a4fb233e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🌞'])[1]/following::h1[1]</value>
      <webElementGuid>f261d84b-b4fc-4d20-9cf6-0fc5ed0ab1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🔍'])[1]/preceding::h1[1]</value>
      <webElementGuid>3e361fdc-8e05-4788-9aa0-e4935b98fb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::h1[1]</value>
      <webElementGuid>4ec1a4cf-1cf2-4cde-8b7b-357efda87c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>825718e0-713a-4220-bda9-37630ed5d56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'flaskBlog' or . = 'flaskBlog')]</value>
      <webElementGuid>990970ef-6562-4c9a-9105-57d7c23e5aa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
